doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'App\Colleges\Infrastructure\Persistence\DoctrineMigrations': '%kernel.project_dir%/src/Colleges/Infrastructure/Persistence/DoctrineMigrations'
    enable_profiler: false
