# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Colleges\Infrastructure\Persistence\Repository\CollegeListRepository:
        arguments: [ '@doctrine' ]

    App\Colleges\Infrastructure\Persistence\Service\CollegeListScraperService:
        arguments:
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
    App\Colleges\Infrastructure\Persistence\Service\CollegeDetailsScraperService:
        arguments:
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'

    App\Colleges\Infrastructure\Persistence\Service\CollegeListPersistenceService:
        arguments:
            $hashGenerator: '@App\Colleges\Infrastructure\Persistence\Service\HashGenerator'
            $collegeListRepository: '@App\Colleges\Infrastructure\Persistence\Repository\CollegeListRepository'
    App\Colleges\Infrastructure\Persistence\Service\CollegeDetailsPersistenceService:
        arguments:
            $collegeDetailsRepository: '@App\Colleges\Infrastructure\Persistence\Repository\CollegeDetailsRepository'

    App\Colleges\Infrastructure\Console\CollectCollegesCommand:
        arguments:
            $collegeListScraperService: '@App\Colleges\Infrastructure\Persistence\Service\CollegeListScraperService'
            $collegeDetailsScraperService: '@App\Colleges\Infrastructure\Persistence\Service\CollegeDetailsScraperService'
            $collegeListPersistenceService: '@App\Colleges\Infrastructure\Persistence\Service\CollegeListPersistenceService'
            $hashGenerator: '@App\Colleges\Infrastructure\Persistence\Service\HashGenerator'
        tags:
            - { name: 'console.command', command: 'app:collect-colleges' }
    App\Colleges\Infrastructure\Console\ClearCollegesCommand:
        arguments:
            $collegeListPersistenceService: '@App\Colleges\Infrastructure\Persistence\Service\CollegeListPersistenceService'
        tags:
            - { name: 'console.command', command: 'app:clear-colleges' }
    App\Colleges\Infrastructure\Console\ShowCollegesCommand:
        arguments:
            $collegeListPersistenceService: '@App\Colleges\Infrastructure\Persistence\Service\CollegeListPersistenceService'
            $collegeDetailsPersistenceService: '@App\Colleges\Infrastructure\Persistence\Service\CollegeDetailsPersistenceService'
        tags:
            - { name: 'console.command', command: 'app:show-colleges' }
