# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Symfony\Component\DomCrawler\Crawler: ~

    Symfony\Component\HttpKernel\HttpCache\Store:
        arguments:
            $root: '%kernel.cache_dir%/http_cache'

    Symfony\Component\HttpClient\CachingHttpClient:
        arguments:
            $client: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $store: '@Symfony\Component\HttpKernel\HttpCache\Store'

    Predis\Client:
        arguments:

    Symfony\Component\Cache\Adapter\RedisAdapter:
        arguments:
            $redis: '@Predis\Client'
            $defaultLifetime: '%env(CACHE_LIFETIME)%'


    App\Command\CollectCollegesCommand:
        arguments:
            $scraperService: '@App\Service\ScraperService'
        tags:
            - { name: 'console.command', command: 'app:collect-colleges' }

    App\Command\ClearCollegesCommand:
        arguments:
            $collegeListService: '@App\Service\CollegeListService'
        tags:
            - { name: 'console.command', command: 'app:clear-colleges' }

    App\Service\ScraperService:
        arguments:
            $scraper: '@App\Service\Scraper\Scraper'
            $pagination: '@App\Service\Scraper\Page\CollegePagination'
            $eventDispatcher: '@Symfony\Component\EventDispatcher\EventDispatcherInterface'
            $collegeDetails: '@App\Service\Scraper\Page\College'
            $collegeDetailsService: '@App\Service\CollegeDetailsService'

    App\Service\CollegeListService:
        public: true
        arguments:
            $collegeListRepository: '@App\Repository\CollegeListRepository'
            $colleges: '@App\Service\Scraper\Page\Colleges'
            $eventDispatcher: '@Symfony\Component\EventDispatcher\EventDispatcherInterface'

    App\Service\CollegeDetailsService:
        arguments:
            $collegeDetailsRepository: '@App\Repository\CollegeDetailsRepository'

    App\Service\CollegesStateService:
        arguments:
            $collegeListRepository: '@App\Repository\CollegeListRepository'
            $cacheService: '@App\Service\Cache\CacheService'
            $hashFactory: '@App\Service\Hash\Md5HashFactory'

    App\Service\Scraper\Scraper:
        arguments:
            $scraper: '@App\Service\Scraper\Common\CachingHttpClientScraper'

    App\Service\Cache\CacheService:
        arguments:
            $cache: '@scraper_pool'

    App\Service\Hash\Md5HashFactory: ~

    App\Service\Scraper\Page\CollegePagination:
        arguments:
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $crawler: '@Symfony\Component\DomCrawler\Crawler'

    App\Service\Scraper\Page\College:
        arguments:
            $crawler: '@Symfony\Component\DomCrawler\Crawler'

    App\Service\Scraper\Page\Colleges:
        arguments:
            $crawler: '@Symfony\Component\DomCrawler\Crawler'

    App\Service\Scraper\Common\BaseScraper:
        arguments:
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'

    App\Service\Scraper\Common\StreamResponsesScraper:
        arguments:
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'

    App\Service\Scraper\Common\CachingHttpClientScraper:
        arguments:
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $store: '@Symfony\Component\HttpKernel\HttpCache\Store'

    App\Event\CollegeListScrapedEvent:
        arguments:
            $contentList: ~

    App\Event\CollegeDetailsScrapedEvent:
        arguments:
            $contentList: ~
